# This rule is not used by the project detection-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to detect.failure-recovery.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: detection-controller
    app.kubernetes.io/managed-by: kustomize
  name: detectiontemplate-viewer-role
rules:
- apiGroups:
  - detect.failure-recovery.io
  resources:
  - detectiontemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - detect.failure-recovery.io
  resources:
  - detectiontemplates/status
  verbs:
  - get
