# This rule is not used by the project conflict-aware-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the recovery.workflow-recovery.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: conflict-aware-controller
    app.kubernetes.io/managed-by: kustomize
  name: recoverytrigger-editor-role
rules:
- apiGroups:
  - recovery.workflow-recovery.io
  resources:
  - recoverytriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recovery.workflow-recovery.io
  resources:
  - recoverytriggers/status
  verbs:
  - get
