# This rule is not used by the project conflict-aware-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over recovery.workflow-recovery.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: conflict-aware-controller
    app.kubernetes.io/managed-by: kustomize
  name: recoverytrigger-admin-role
rules:
- apiGroups:
  - recovery.workflow-recovery.io
  resources:
  - recoverytriggers
  verbs:
  - '*'
- apiGroups:
  - recovery.workflow-recovery.io
  resources:
  - recoverytriggers/status
  verbs:
  - get
