apiVersion: recovery.workflow-recovery.io/v1alpha1
kind: RecoveryTrigger
metadata:
  name: node-recovery-trigger-1
  namespace: default
spec:
  failureType: NodeFailure
  workflowTemplate: node-recovery-template
  targetObjects:
    - kind: Node
      name: worker-1
